### PR TITLE
fix(tag-values): fixed boolean tag values returning wrong values

### LINKED ISSUE #1602: 🐞 Issue with Custom Boolean Filter in Teletrace
# Describe the Bug
When attempting to add a custom boolean filter in Teletrace, the search results display "No matching spans found" instead of the expected results.

## Steps To Reproduce

1. Run Teletrace OpenTelemetry demo. 
2. Navigate to the Teletrace application.
3. Add a custom boolean filter. (span.attributes.app.cache_hit)
4. Set the filter value to either 0 or 1.
5. Perform a search based on the filter criteria.
6. Observe the search results displaying "No matching spans found" instead of the expected results.

## Expected Behavior
The search results should display spans that match the custom boolean filter criteria.

## Environment:

- Infrastructure: laptop
- Deployment tool: docker-compose (Otel Demo)
- Browser: Chrome
- OS: IOS

## Screenshots
Screenshot 2023-05-15 at 11 07 18
Screenshot 2023-05-15 at 11 07 04

### PR DESCRIPTION
**Pull request by tvaintrob**
## What this PR does:

fix boolean filters not showing correct values

## Which issue(s) this PR fixes:

Fixes #1602

### CODE REVIEW

File: plugin/spanreader/es/tagscontroller/tags_controller.go [hunk 1]
```diff
@@ -328,6 +328,12 @@ func (r *tagsController) parseGetTagsValuesResponseBody(
 			for _, v := range aggregation["buckets"].([]any) {
 				bucket := v.(map[string]any)
 				value := bucket["key"]
+
+				// handle boolean fields
+				if kas, ok := bucket["key_as_string"]; ok {
```
Comment (haimrait) [inline plugin/spanreader/es/tagscontroller/tags_controller.go:333]: Will it show true or false for boolean params or 1 and 0?
Because I think we need to change this as well

**Review by haimrait — APPROVED** [review]

**Comment by haimrait** [comment]
Mergifyio refresh
